### ISSUE TITLE
Error: spawn ENAMETOOLONG on Windows 10

### ISSUE THREAD

**Issue by hypery2k** [Turbo87/webpack-notifier#20]
Issues when using plugin on Windows 10, see https://github.com/mikaelbr/node-notifier/issues/145

**Comment by hypery2k** [comment]
or maybe this one is better: https://github.com/karma-runner/grunt-karma/pull/163/files

**Comment by guylando** [comment]
This issue prevents us from using this plugin

**Comment by meikeric** [comment]
Had this issue when build an app on Windows 10, disabled this plugin in webpack.  Build fine...

**Comment by Gvozd** [comment]
Is this a pressing problem?
try version 1.9.0 or newer

For this version, I managed to artificially call it by setting a message with a length of more than 32000 characters
If the message is longer than ~ 5000 characters, then there is no error, but the notification is no longer displayed

These are large enough messages, and I'm not sure if they are encountered in practice, especially 32000
If the problem persists, can you provide a reproducible example?

In any case, you can try to trim messages
But I would like to know what these limits depend on, and how to determine / set them, except for heuristic selection
Anyone have any ideas on this?

**Comment by Gvozd** [comment]
reopen in the case of repetition

**Comment by wolfingduck** [comment]
Hello,
I have the same problem:
[INFO] node:internal/errors:464
[INFO]     ErrorCaptureStackTrace(err);
[INFO]     ^
[INFO]
[INFO] Error: spawn ENAMETOOLONG
[INFO]     at ChildProcess.spawn (node:internal/child_process:412:11)
[INFO]     at spawn (node:child_process:698:9)
[INFO]     at Object.execFile (node:child_process:325:17)
[INFO]     at Object.module.exports.fileCommand (E:\jhispster\my_proj\node_modules\webpack-notifier\node_modules\node-notifier\lib\utils.js:76:13)
[INFO]     at E:\jhispster\my_proj\node_modules\webpack-notifier\node_modules\node-notifier\notifiers\toaster.js:145:11
[INFO]     at runMicrotasks (<anonymous>)
[INFO]     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
[INFO]   errno: -4064,
[INFO]   code: 'ENAMETOOLONG',
[INFO]   syscall: 'spawn'
[INFO] }
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] -----------------------------


Anyone have any ideas on this?

**Comment by Gvozd** [comment]
E:\ is phisical drive, or mounted to network share, or some sync tools, like google drive?

**Comment by wolfingduck** [comment]
E:\ is a physical drive with file system nyfs.
I have already allowed my windows 10 pro to support long path

**Comment by Gvozd** [comment]
Please run your webpack with env variable `DEBUG="notifier"`, and pipe stdout to file
I need the latest `[notifier path]`, `[notifier options]` from the log
Also I need your plugin configuration

**Comment by Hiisham89** [comment]
hello i have the same problem
webpack 5.95.0 compiled with 1 error in 62692 ms
node:internal/child_process:420
    throw new ErrnoException(err, 'spawn');
          ^

Error: spawn ENAMETOOLONG
    at ChildProcess.spawn (node:internal/child_process:420:11)
    at spawn (node:child_process:759:9)
    at Object.execFile (node:child_process:350:17)
    at module.exports.fileCommand (D:\constructionpermit\node_modules\node-notifier\lib\utils.js:76:13)
    at D:\constructionpermit\node_modules\node-notifier\notifiers\toaster.js:145:11
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
  errno: -4064,
  code: 'ENAMETOOLONG',
  syscall: 'spawn'
}

Node.js v22.11.0

**Comment by Hiisham89** [comment]
i have just solved my error by disabling the prettier in eslint file, befor the above error had shown i had 1000 error for prettier.

**Comment by haroonmohammadi24** [comment]
thanks mr [Hiisham89](https://github.com/Hiisham89) you solution is fit to my problem sir

**Comment by Gvozd** [comment]
fix published as 1.16.0
