### ISSUE TITLE
Does not work - Cannot read property 'mangleWasmImports' of undefined

### ISSUE THREAD

**Issue by nextgenthemes** [Turbo87/webpack-notifier#76]
Ubuntu 22.04

```
[webpack-cli] TypeError: Cannot read property 'mangleWasmImports' of undefined
    at EnableWasmLoadingPlugin.apply (/path/node_modules/webpack/lib/wasm/EnableWasmLoadingPlugin.js:79:52)
    at WebpackOptionsApply.process (/path/node_modules/webpack/lib/WebpackOptionsApply.js:223:39)
    at createCompiler (/path/node_modules/webpack/lib/webpack.js:80:28)
    at create (/path/node_modules/webpack/lib/webpack.js:134:16)
    at webpack (/path/node_modules/webpack/lib/webpack.js:142:47)
    at WebpackCLI.f [as webpack] (/path/node_modules/webpack/lib/index.js:64:16)
    at WebpackCLI.createCompiler (/path/node_modules/webpack-cli/lib/webpack-cli.js:1789:29)
    at async WebpackCLI.runWebpack (/path/node_modules/webpack-cli/lib/webpack-cli.js:1890:20)
    at async Command.<anonymous> (/path/node_modules/webpack-cli/lib/webpack-cli.js:912:21)
    at async Promise.all (index 1)
```

**Comment by nextgenthemes** [comment]
Nevermind forgot the `new` in the config.
